source 'https://github.com/CocoaPods/Specs.git'
#use_frameworks!

target 'NHVideoPlayer_Example', :exclusive => true do
  pod "NHVideoPlayer", :path => "../"
end

target 'NHVideoPlayer_Tests', :exclusive => true do
  pod "NHVideoPlayer", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
